export const ACCOUNT_LIMITS = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
};

export const CATEGORY_LIMITS = {
  NAME_MAX_LENGTH: 50,
};

export const TRANSACTION_LIMITS = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 100,
};

export const TRANSACTION_FILTER_LIMITS = {
  MONTH_MIN: 1,
  MONTH_MAX: 12,
  YEAR_MIN: 2020,
  YEAR_MAX: 2100,
  RESULTS_MIN: 1,
  RESULTS_MAX: 100,
};

export const ANALYTICS_LIMITS = {
  MONTH_MIN: 1,
  MONTH_MAX: 12,
  YEAR_MIN: 2020,
  YEAR_MAX: 2100,
};
