export const ACCOUNT_LIMITS = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
};

export const CATEGORY_LIMITS = {
  NAME_MAX_LENGTH: 50,
};

export const TRANSACTION_LIMITS = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 100,
};
